apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress-backend
  name: wordpress-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-backend
  template:
    metadata:
      labels:
        app: wordpress-backend
    spec:
      containers:
        - name: wordpress-backend
          image: wordpress:5.6
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
          env:
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DB_MASTER_HOST
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: DATABASE_NAME
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "200m"